Clean booking rspec
commit-tech/nussu-logistics pull request #27
Opened 2019-03-27 12:23 UTC by NicholasCF

Fixes #20. 

Changed the quantity validation.
Checked with rspec, but the test name and implementation may be lacking.

2019-04-03 02:12 UTC, NicholasCF commented
There's an issue with the counting, working on it

2019-04-06 02:58 UTC, NicholasCF commented
The quantity validation now correctly bases itself on the total quantity of reserved item, instead of the total number of bookings

2019-04-06 03:25 UTC, NicholasCF commented
I added the ability for curr to jump to the next start_time, instead of incrementing in 30 minutes

2019-04-13 08:55 UTC, sreycodes requested changes

2019-04-13 08:55 UTC, sreycodes commented on spec/controllers/bookings_controller_spec.rb
> +      user.add_role(:technical)
Technically add_role shouldn't work. Don't do this here

2019-04-13 08:55 UTC, sreycodes commented on spec/controllers/bookings_controller_spec.rb
> +
Add a test changing to a quantity greater than the item.quantity and make sure it doesn't work

2019-04-13 09:55 UTC, sreycodes approved these changes

2019-04-13 09:56 UTC, merged